name: 'Run Backport Bot'
description: 'Run Backport Bot'

inputs:
  token:
    description: 'A GitHub token for gh api calls'
    required: true

runs:
  using: composite
  steps:
    - uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: 17

    - name: Download Backport Bot jar from release asset
      shell: bash
      run: gh release download "${{ github.action_ref }}" --repo "$GITHUB_REPOSITORY" --pattern "backport-bot-*.jar"
      env:
        GH_TOKEN: ${{ inputs.token }}

    - name: Run Backport Bot jar
      shell: bash
      run: java -jar backport-bot-${{ github.action_ref }}.jar \
        --github.accessToken="${{ inputs.token }}" \
        --github.event_name="${{ github.event_name }}" \
        --github.event="${{ toJSON(github.event) }}"
      env:
        SPRING_MAIN_BANNERMODE: off
