name: 'Run Backport Bot'
description: 'Run Backport Bot'

inputs:
  token:
    description: 'A GitHub token for gh api calls'
    required: true

runs:
  using: composite
  steps:
    - uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: 17

    - name: Download Backport Bot jar and run
      shell: bash
      run: |
        gh release download "$ACTION_VERSION" --repo spring-io/backport-bot --pattern "backport-bot-*.jar"
        
        jars=( ./*.jar )

        java -jar "${jars[0]}" \
              --github.accessToken="$GH_TOKEN" \
              --github.event_name "$GITHUB_EVENT_NAME" \
              --github.event "$GITHUB_EVENT"
      env:
        GH_TOKEN: ${{ inputs.token }}
        ACTION_VERSION: ${{ github.action_ref }}
        GITHUB_EVENT: ${{ toJSON(github.event) }}
        SPRING_MAIN_BANNERMODE: off
