BackportBot handles backports

= Behavior

The BackportBot assists in creating backport issues and automatically closing backport issues.

== Creating Backport

The BackportBot can create issues in two different ways.
In either case the following logic is used:

* If backport issue does not exist:
  * Create a new backport issue with the additional label `is: backport`
  * Update the existing issue with the label `is: backported`
* Automatically remove the `backport: <branch-name>` label from the existing issue

=== Via Labels

You can add a label in the form of `backport: <branch-name>` (i.e. backport: 5.1.x) and
adding the label to a ticket will create a backport for the branch `<branch-name` (i.e. 5.1.x).

=== Pushing to Branch

You can create a backport by pushing to a branch that ends in `.x` with `Fixes: gh-<number>` in the commit message.

== Closing Backport

If a branch ending in `.x` is pushed to, the BackportBot will look at the commit message for the pattern `Fixes: gh-<number>`.
If the pattern is found, it looks up the issue `<number>` and closes the backport that has a milestone corresponding to the gradle.properties in the branch that is being pushed to.