package io.spring.github

import io.spring.github.api.Issue
import io.spring.github.api.PullRequest
import io.spring.github.event.GitHubHooksController
import io.spring.github.event.IssueEvent
import io.spring.github.event.PullRequestEvent
import io.spring.github.event.PullRequestEvent.Repository
import io.spring.github.event.PushEvent
import org.junit.jupiter.api.Test
import org.mockito.kotlin.any
import org.mockito.kotlin.mock
import org.mockito.kotlin.verify
import org.mockito.kotlin.whenever
import org.springframework.boot.SpringApplication

class BackportBotCommandLineRunnerTest {

    @Test
    fun pullRequestLabeled() {
        val controller : GitHubHooksController = mock()
        whenever(controller.githubPullRequestEvent(any())).thenReturn(GitHubHooksController.Result.CREATED)
        val application = SpringApplication(BackportBotApplication::class.java)
        application.addInitializers(ReplaceBeanInitializer(GitHubHooksController::class.java, controller))
        application.run("--github.accessToken", "some-secret", "--github.event_name", "pull_request", "--github_event", pullRequestLabeledBody).use { }
        val pullRequest = PullRequest(156, "Here it is", null, listOf(PullRequest.Label("for: backport-to-1.0.x"), PullRequest.Label("for: backport-to-1.1.x")))
        verify(controller).githubPullRequestEvent(PullRequestEvent("labeled", Repository("rwinch/deleteme-backport-test"), PullRequestEvent.Label("for: backport-to-1.1.x"), pullRequest))
    }

    @Test
    fun issueLabeled() {
        val controller : GitHubHooksController = mock()
        whenever(controller.githubEvent(any())).thenReturn(GitHubHooksController.Result.CREATED)
        val application = SpringApplication(BackportBotApplication::class.java)
        application.addInitializers(ReplaceBeanInitializer(GitHubHooksController::class.java, controller))
        application.run("--github.accessToken", "some-secret", "--github.event_name", "issues", "--github_event", issueLabeledBody).use { }
        val issueEvent = IssueEvent("labeled", IssueEvent.Repository("rwinch/deleteme-backport-test"), IssueEvent.Sender("rwinch"), IssueEvent.Label("backport: 1.0.x"), Issue(40, "An Issue", null, listOf(Issue.Label("backport: 1.0.x"))))
        verify(controller).githubEvent(issueEvent)
    }

    @Test
    fun pushEvent() {
        val controller : GitHubHooksController = mock()
        whenever(controller.githubEventPush(any())).thenReturn(GitHubHooksController.Result.CREATED)
        val application = SpringApplication(BackportBotApplication::class.java)
        application.addInitializers(ReplaceBeanInitializer(GitHubHooksController::class.java, controller))
        application.run("--github.accessToken", "some-secret", "--github.event_name", "push", "--github_event", pushEventBody).use { }
        val pushEvent = PushEvent("refs/heads/main", PushEvent.Repository("spring-projects/spring-security"), PushEvent.Pusher("rwinch"), listOf(PushEvent.Commit("60fc5381fe9f094e56bbb279b857eaec318f5c0f", "Fixed Git SCM book link")))
        verify(controller).githubEventPush(pushEvent)
    }

    val issueLabeledBody = """
    {
      "action": "labeled",
      "issue": {
        "url": "https://api.github.com/repos/rwinch/deleteme-backport-test/issues/40",
        "repository_url": "https://api.github.com/repos/rwinch/deleteme-backport-test",
        "labels_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/issues/40/labels{/name}",
        "comments_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/issues/40/comments",
        "events_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/issues/40/events",
        "html_url": "https://github.com/rwinch/deleteme-backport-test/issues/40",
        "id": 393200171,
        "node_id": "MDU6SXNzdWUzOTMyMDAxNzE=",
        "number": 40,
        "title": "An Issue",
        "user": {
          "login": "rwinch",
          "id": 362503,
          "node_id": "MDQ6VXNlcjM2MjUwMw==",
          "avatar_url": "https://avatars0.githubusercontent.com/u/362503?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/rwinch",
          "html_url": "https://github.com/rwinch",
          "followers_url": "https://api.github.com/users/rwinch/followers",
          "following_url": "https://api.github.com/users/rwinch/following{/other_user}",
          "gists_url": "https://api.github.com/users/rwinch/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/rwinch/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/rwinch/subscriptions",
          "organizations_url": "https://api.github.com/users/rwinch/orgs",
          "repos_url": "https://api.github.com/users/rwinch/repos",
          "events_url": "https://api.github.com/users/rwinch/events{/privacy}",
          "received_events_url": "https://api.github.com/users/rwinch/received_events",
          "type": "User",
          "site_admin": false
        },
        "labels": [
          {
            "id": 1166036400,
            "node_id": "MDU6TGFiZWwxMTY2MDM2NDAw",
            "url": "https://api.github.com/repos/rwinch/deleteme-backport-test/labels/backport:%201.0.x",
            "name": "backport: 1.0.x",
            "color": "006b75",
            "default": false
          }
        ],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [

        ],
        "milestone": null,
        "comments": 0,
        "created_at": "2018-12-20T20:28:21Z",
        "updated_at": "2018-12-20T20:41:13Z",
        "closed_at": null,
        "author_association": "OWNER",
        "body": "The body"
      },
      "label": {
        "id": 1166036400,
        "node_id": "MDU6TGFiZWwxMTY2MDM2NDAw",
        "url": "https://api.github.com/repos/rwinch/deleteme-backport-test/labels/backport:%201.0.x",
        "name": "backport: 1.0.x",
        "color": "006b75",
        "default": false
      },
      "repository": {
        "id": 160412400,
        "node_id": "MDEwOlJlcG9zaXRvcnkxNjA0MTI0MDA=",
        "name": "deleteme-backport-test",
        "full_name": "rwinch/deleteme-backport-test",
        "private": false,
        "owner": {
          "login": "rwinch",
          "id": 362503,
          "node_id": "MDQ6VXNlcjM2MjUwMw==",
          "avatar_url": "https://avatars0.githubusercontent.com/u/362503?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/rwinch",
          "html_url": "https://github.com/rwinch",
          "followers_url": "https://api.github.com/users/rwinch/followers",
          "following_url": "https://api.github.com/users/rwinch/following{/other_user}",
          "gists_url": "https://api.github.com/users/rwinch/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/rwinch/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/rwinch/subscriptions",
          "organizations_url": "https://api.github.com/users/rwinch/orgs",
          "repos_url": "https://api.github.com/users/rwinch/repos",
          "events_url": "https://api.github.com/users/rwinch/events{/privacy}",
          "received_events_url": "https://api.github.com/users/rwinch/received_events",
          "type": "User",
          "site_admin": false
        },
        "html_url": "https://github.com/rwinch/deleteme-backport-test",
        "description": null,
        "fork": false,
        "url": "https://api.github.com/repos/rwinch/deleteme-backport-test",
        "forks_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/forks",
        "keys_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/teams",
        "hooks_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/hooks",
        "issue_events_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/issues/events{/number}",
        "events_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/events",
        "assignees_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/assignees{/user}",
        "branches_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/branches{/branch}",
        "tags_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/tags",
        "blobs_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/languages",
        "stargazers_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/stargazers",
        "contributors_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/contributors",
        "subscribers_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/subscribers",
        "subscription_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/subscription",
        "commits_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/contents/{+path}",
        "compare_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/merges",
        "archive_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/downloads",
        "issues_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/issues{/number}",
        "pulls_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/labels{/name}",
        "releases_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/releases{/id}",
        "deployments_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/deployments",
        "created_at": "2018-12-04T20:05:53Z",
        "updated_at": "2018-12-05T20:33:00Z",
        "pushed_at": "2018-12-13T21:03:38Z",
        "git_url": "git://github.com/rwinch/deleteme-backport-test.git",
        "ssh_url": "git@github.com:rwinch/deleteme-backport-test.git",
        "clone_url": "https://github.com/rwinch/deleteme-backport-test.git",
        "svn_url": "https://github.com/rwinch/deleteme-backport-test",
        "homepage": null,
        "size": 12,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": null,
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "open_issues_count": 3,
        "license": null,
        "forks": 0,
        "open_issues": 3,
        "watchers": 0,
        "default_branch": "main"
      },
      "sender": {
        "login": "rwinch",
        "id": 362503,
        "node_id": "MDQ6VXNlcjM2MjUwMw==",
        "avatar_url": "https://avatars0.githubusercontent.com/u/362503?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/rwinch",
        "html_url": "https://github.com/rwinch",
        "followers_url": "https://api.github.com/users/rwinch/followers",
        "following_url": "https://api.github.com/users/rwinch/following{/other_user}",
        "gists_url": "https://api.github.com/users/rwinch/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/rwinch/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/rwinch/subscriptions",
        "organizations_url": "https://api.github.com/users/rwinch/orgs",
        "repos_url": "https://api.github.com/users/rwinch/repos",
        "events_url": "https://api.github.com/users/rwinch/events{/privacy}",
        "received_events_url": "https://api.github.com/users/rwinch/received_events",
        "type": "User",
        "site_admin": false
      }
    }"""

    val pullRequestLabeledBody = """{
  "action": "labeled",
  "number": 156,
  "pull_request": {
    "url": "https://api.github.com/repos/rwinch/deleteme-backport-test/pulls/156",
    "id": 254095638,
    "node_id": "MDExOlB1bGxSZXF1ZXN0MjU0MDk1NjM4",
    "html_url": "https://github.com/rwinch/deleteme-backport-test/pull/156",
    "diff_url": "https://github.com/rwinch/deleteme-backport-test/pull/156.diff",
    "patch_url": "https://github.com/rwinch/deleteme-backport-test/pull/156.patch",
    "issue_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/issues/156",
    "number": 156,
    "state": "open",
    "locked": false,
    "title": "Here it is",
    "user": {
      "login": "rwinch",
      "id": 362503,
      "node_id": "MDQ6VXNlcjM2MjUwMw==",
      "avatar_url": "https://avatars0.githubusercontent.com/u/362503?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rwinch",
      "html_url": "https://github.com/rwinch",
      "followers_url": "https://api.github.com/users/rwinch/followers",
      "following_url": "https://api.github.com/users/rwinch/following{/other_user}",
      "gists_url": "https://api.github.com/users/rwinch/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/rwinch/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/rwinch/subscriptions",
      "organizations_url": "https://api.github.com/users/rwinch/orgs",
      "repos_url": "https://api.github.com/users/rwinch/repos",
      "events_url": "https://api.github.com/users/rwinch/events{/privacy}",
      "received_events_url": "https://api.github.com/users/rwinch/received_events",
      "type": "User",
      "site_admin": false
    },
    "body": "",
    "created_at": "2019-02-19T02:35:57Z",
    "updated_at": "2019-02-19T02:36:28Z",
    "closed_at": null,
    "merged_at": null,
    "merge_commit_sha": "90babfd4cf682bfce15be6c62f34bbc533c23161",
    "assignee": null,
    "assignees": [

    ],
    "requested_reviewers": [

    ],
    "requested_teams": [

    ],
    "labels": [
      {
        "id": 1166036400,
        "node_id": "MDU6TGFiZWwxMTY2MDM2NDAw",
        "url": "https://api.github.com/repos/rwinch/deleteme-backport-test/labels/for:%20backport-to-1.0.x",
        "name": "for: backport-to-1.0.x",
        "color": "fbca04",
        "default": false
      },
      {
        "id": 1168377027,
        "node_id": "MDU6TGFiZWwxMTY4Mzc3MDI3",
        "url": "https://api.github.com/repos/rwinch/deleteme-backport-test/labels/for:%20backport-to-1.1.x",
        "name": "for: backport-to-1.1.x",
        "color": "fbca04",
        "default": false
      }
    ],
    "milestone": null,
    "commits_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/pulls/156/commits",
    "review_comments_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/pulls/156/comments",
    "review_comment_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/pulls/comments{/number}",
    "comments_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/issues/156/comments",
    "statuses_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/statuses/080536b061193cbf3065a7c70a37c228ba995524",
    "head": {
      "label": "rwinch:main",
      "ref": "main",
      "sha": "080536b061193cbf3065a7c70a37c228ba995524",
      "user": {
        "login": "rwinch",
        "id": 362503,
        "node_id": "MDQ6VXNlcjM2MjUwMw==",
        "avatar_url": "https://avatars0.githubusercontent.com/u/362503?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/rwinch",
        "html_url": "https://github.com/rwinch",
        "followers_url": "https://api.github.com/users/rwinch/followers",
        "following_url": "https://api.github.com/users/rwinch/following{/other_user}",
        "gists_url": "https://api.github.com/users/rwinch/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/rwinch/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/rwinch/subscriptions",
        "organizations_url": "https://api.github.com/users/rwinch/orgs",
        "repos_url": "https://api.github.com/users/rwinch/repos",
        "events_url": "https://api.github.com/users/rwinch/events{/privacy}",
        "received_events_url": "https://api.github.com/users/rwinch/received_events",
        "type": "User",
        "site_admin": false
      },
      "repo": {
        "id": 160412400,
        "node_id": "MDEwOlJlcG9zaXRvcnkxNjA0MTI0MDA=",
        "name": "deleteme-backport-test",
        "full_name": "rwinch/deleteme-backport-test",
        "private": false,
        "owner": {
          "login": "rwinch",
          "id": 362503,
          "node_id": "MDQ6VXNlcjM2MjUwMw==",
          "avatar_url": "https://avatars0.githubusercontent.com/u/362503?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/rwinch",
          "html_url": "https://github.com/rwinch",
          "followers_url": "https://api.github.com/users/rwinch/followers",
          "following_url": "https://api.github.com/users/rwinch/following{/other_user}",
          "gists_url": "https://api.github.com/users/rwinch/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/rwinch/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/rwinch/subscriptions",
          "organizations_url": "https://api.github.com/users/rwinch/orgs",
          "repos_url": "https://api.github.com/users/rwinch/repos",
          "events_url": "https://api.github.com/users/rwinch/events{/privacy}",
          "received_events_url": "https://api.github.com/users/rwinch/received_events",
          "type": "User",
          "site_admin": false
        },
        "html_url": "https://github.com/rwinch/deleteme-backport-test",
        "description": null,
        "fork": false,
        "url": "https://api.github.com/repos/rwinch/deleteme-backport-test",
        "forks_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/forks",
        "keys_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/teams",
        "hooks_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/hooks",
        "issue_events_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/issues/events{/number}",
        "events_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/events",
        "assignees_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/assignees{/user}",
        "branches_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/branches{/branch}",
        "tags_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/tags",
        "blobs_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/languages",
        "stargazers_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/stargazers",
        "contributors_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/contributors",
        "subscribers_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/subscribers",
        "subscription_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/subscription",
        "commits_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/contents/{+path}",
        "compare_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/merges",
        "archive_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/downloads",
        "issues_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/issues{/number}",
        "pulls_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/labels{/name}",
        "releases_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/releases{/id}",
        "deployments_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/deployments",
        "created_at": "2018-12-04T20:05:53Z",
        "updated_at": "2019-02-07T06:19:54Z",
        "pushed_at": "2019-02-19T02:35:58Z",
        "git_url": "git://github.com/rwinch/deleteme-backport-test.git",
        "ssh_url": "git@github.com:rwinch/deleteme-backport-test.git",
        "clone_url": "https://github.com/rwinch/deleteme-backport-test.git",
        "svn_url": "https://github.com/rwinch/deleteme-backport-test",
        "homepage": null,
        "size": 4,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": null,
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "open_issues_count": 1,
        "license": null,
        "forks": 0,
        "open_issues": 1,
        "watchers": 0,
        "default_branch": "main"
      }
    },
    "base": {
      "label": "rwinch:1.1.x",
      "ref": "1.1.x",
      "sha": "76acb2d7ac8761b89d52f8be4ac6840089f3e792",
      "user": {
        "login": "rwinch",
        "id": 362503,
        "node_id": "MDQ6VXNlcjM2MjUwMw==",
        "avatar_url": "https://avatars0.githubusercontent.com/u/362503?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/rwinch",
        "html_url": "https://github.com/rwinch",
        "followers_url": "https://api.github.com/users/rwinch/followers",
        "following_url": "https://api.github.com/users/rwinch/following{/other_user}",
        "gists_url": "https://api.github.com/users/rwinch/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/rwinch/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/rwinch/subscriptions",
        "organizations_url": "https://api.github.com/users/rwinch/orgs",
        "repos_url": "https://api.github.com/users/rwinch/repos",
        "events_url": "https://api.github.com/users/rwinch/events{/privacy}",
        "received_events_url": "https://api.github.com/users/rwinch/received_events",
        "type": "User",
        "site_admin": false
      },
      "repo": {
        "id": 160412400,
        "node_id": "MDEwOlJlcG9zaXRvcnkxNjA0MTI0MDA=",
        "name": "deleteme-backport-test",
        "full_name": "rwinch/deleteme-backport-test",
        "private": false,
        "owner": {
          "login": "rwinch",
          "id": 362503,
          "node_id": "MDQ6VXNlcjM2MjUwMw==",
          "avatar_url": "https://avatars0.githubusercontent.com/u/362503?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/rwinch",
          "html_url": "https://github.com/rwinch",
          "followers_url": "https://api.github.com/users/rwinch/followers",
          "following_url": "https://api.github.com/users/rwinch/following{/other_user}",
          "gists_url": "https://api.github.com/users/rwinch/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/rwinch/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/rwinch/subscriptions",
          "organizations_url": "https://api.github.com/users/rwinch/orgs",
          "repos_url": "https://api.github.com/users/rwinch/repos",
          "events_url": "https://api.github.com/users/rwinch/events{/privacy}",
          "received_events_url": "https://api.github.com/users/rwinch/received_events",
          "type": "User",
          "site_admin": false
        },
        "html_url": "https://github.com/rwinch/deleteme-backport-test",
        "description": null,
        "fork": false,
        "url": "https://api.github.com/repos/rwinch/deleteme-backport-test",
        "forks_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/forks",
        "keys_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/teams",
        "hooks_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/hooks",
        "issue_events_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/issues/events{/number}",
        "events_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/events",
        "assignees_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/assignees{/user}",
        "branches_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/branches{/branch}",
        "tags_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/tags",
        "blobs_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/languages",
        "stargazers_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/stargazers",
        "contributors_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/contributors",
        "subscribers_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/subscribers",
        "subscription_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/subscription",
        "commits_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/contents/{+path}",
        "compare_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/merges",
        "archive_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/downloads",
        "issues_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/issues{/number}",
        "pulls_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/labels{/name}",
        "releases_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/releases{/id}",
        "deployments_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/deployments",
        "created_at": "2018-12-04T20:05:53Z",
        "updated_at": "2019-02-07T06:19:54Z",
        "pushed_at": "2019-02-19T02:35:58Z",
        "git_url": "git://github.com/rwinch/deleteme-backport-test.git",
        "ssh_url": "git@github.com:rwinch/deleteme-backport-test.git",
        "clone_url": "https://github.com/rwinch/deleteme-backport-test.git",
        "svn_url": "https://github.com/rwinch/deleteme-backport-test",
        "homepage": null,
        "size": 4,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": null,
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "open_issues_count": 1,
        "license": null,
        "forks": 0,
        "open_issues": 1,
        "watchers": 0,
        "default_branch": "main"
      }
    },
    "_links": {
      "self": {
        "href": "https://api.github.com/repos/rwinch/deleteme-backport-test/pulls/156"
      },
      "html": {
        "href": "https://github.com/rwinch/deleteme-backport-test/pull/156"
      },
      "issue": {
        "href": "https://api.github.com/repos/rwinch/deleteme-backport-test/issues/156"
      },
      "comments": {
        "href": "https://api.github.com/repos/rwinch/deleteme-backport-test/issues/156/comments"
      },
      "review_comments": {
        "href": "https://api.github.com/repos/rwinch/deleteme-backport-test/pulls/156/comments"
      },
      "review_comment": {
        "href": "https://api.github.com/repos/rwinch/deleteme-backport-test/pulls/comments{/number}"
      },
      "commits": {
        "href": "https://api.github.com/repos/rwinch/deleteme-backport-test/pulls/156/commits"
      },
      "statuses": {
        "href": "https://api.github.com/repos/rwinch/deleteme-backport-test/statuses/080536b061193cbf3065a7c70a37c228ba995524"
      }
    },
    "author_association": "OWNER",
    "draft": false,
    "merged": false,
    "mergeable": true,
    "rebaseable": true,
    "mergeable_state": "clean",
    "merged_by": null,
    "comments": 0,
    "review_comments": 0,
    "maintainer_can_modify": false,
    "commits": 1,
    "additions": 1,
    "deletions": 1,
    "changed_files": 1
  },
  "label": {
    "id": 1168377027,
    "node_id": "MDU6TGFiZWwxMTY4Mzc3MDI3",
    "url": "https://api.github.com/repos/rwinch/deleteme-backport-test/labels/for:%20backport-to-1.1.x",
    "name": "for: backport-to-1.1.x",
    "color": "fbca04",
    "default": false
  },
  "repository": {
    "id": 160412400,
    "node_id": "MDEwOlJlcG9zaXRvcnkxNjA0MTI0MDA=",
    "name": "deleteme-backport-test",
    "full_name": "rwinch/deleteme-backport-test",
    "private": false,
    "owner": {
      "login": "rwinch",
      "id": 362503,
      "node_id": "MDQ6VXNlcjM2MjUwMw==",
      "avatar_url": "https://avatars0.githubusercontent.com/u/362503?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rwinch",
      "html_url": "https://github.com/rwinch",
      "followers_url": "https://api.github.com/users/rwinch/followers",
      "following_url": "https://api.github.com/users/rwinch/following{/other_user}",
      "gists_url": "https://api.github.com/users/rwinch/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/rwinch/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/rwinch/subscriptions",
      "organizations_url": "https://api.github.com/users/rwinch/orgs",
      "repos_url": "https://api.github.com/users/rwinch/repos",
      "events_url": "https://api.github.com/users/rwinch/events{/privacy}",
      "received_events_url": "https://api.github.com/users/rwinch/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/rwinch/deleteme-backport-test",
    "description": null,
    "fork": false,
    "url": "https://api.github.com/repos/rwinch/deleteme-backport-test",
    "forks_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/forks",
    "keys_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/teams",
    "hooks_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/hooks",
    "issue_events_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/issues/events{/number}",
    "events_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/events",
    "assignees_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/assignees{/user}",
    "branches_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/branches{/branch}",
    "tags_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/tags",
    "blobs_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/languages",
    "stargazers_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/stargazers",
    "contributors_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/contributors",
    "subscribers_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/subscribers",
    "subscription_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/subscription",
    "commits_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/contents/{+path}",
    "compare_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/merges",
    "archive_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/downloads",
    "issues_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/issues{/number}",
    "pulls_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/labels{/name}",
    "releases_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/releases{/id}",
    "deployments_url": "https://api.github.com/repos/rwinch/deleteme-backport-test/deployments",
    "created_at": "2018-12-04T20:05:53Z",
    "updated_at": "2019-02-07T06:19:54Z",
    "pushed_at": "2019-02-19T02:35:58Z",
    "git_url": "git://github.com/rwinch/deleteme-backport-test.git",
    "ssh_url": "git@github.com:rwinch/deleteme-backport-test.git",
    "clone_url": "https://github.com/rwinch/deleteme-backport-test.git",
    "svn_url": "https://github.com/rwinch/deleteme-backport-test",
    "homepage": null,
    "size": 4,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": null,
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "open_issues_count": 1,
    "license": null,
    "forks": 0,
    "open_issues": 1,
    "watchers": 0,
    "default_branch": "main"
  },
  "sender": {
    "login": "rwinch",
    "id": 362503,
    "node_id": "MDQ6VXNlcjM2MjUwMw==",
    "avatar_url": "https://avatars0.githubusercontent.com/u/362503?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/rwinch",
    "html_url": "https://github.com/rwinch",
    "followers_url": "https://api.github.com/users/rwinch/followers",
    "following_url": "https://api.github.com/users/rwinch/following{/other_user}",
    "gists_url": "https://api.github.com/users/rwinch/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/rwinch/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/rwinch/subscriptions",
    "organizations_url": "https://api.github.com/users/rwinch/orgs",
    "repos_url": "https://api.github.com/users/rwinch/repos",
    "events_url": "https://api.github.com/users/rwinch/events{/privacy}",
    "received_events_url": "https://api.github.com/users/rwinch/received_events",
    "type": "User",
    "site_admin": false
  }
}"""

    val pushEventBody = """
        {
          "ref": "refs/heads/main",
          "before": "2cb8794e355e94c0568f1085d51986e76ad2a204",
          "after": "60fc5381fe9f094e56bbb279b857eaec318f5c0f",
          "created": false,
          "deleted": false,
          "forced": false,
          "base_ref": null,
          "compare": "https://github.com/spring-projects/spring-security/compare/2cb8794e355e...60fc5381fe9f",
          "commits": [
            {
              "id": "60fc5381fe9f094e56bbb279b857eaec318f5c0f",
              "tree_id": "ff05f721f3f5439824f4d16c074909d63fc34778",
              "distinct": true,
              "message": "Fixed Git SCM book link",
              "timestamp": "2018-11-30T14:54:46-06:00",
              "url": "https://github.com/spring-projects/spring-security/commit/60fc5381fe9f094e56bbb279b857eaec318f5c0f",
              "author": {
                "name": "mibo",
                "email": "mibo@users.noreply.github.com",
                "username": "mibo"
              },
              "committer": {
                "name": "Rob Winch",
                "email": "rwinch@users.noreply.github.com",
                "username": "rwinch"
              },
              "added": [

              ],
              "removed": [

              ],
              "modified": [
                "CONTRIBUTING.md"
              ]
            }
          ],
          "head_commit": {
            "id": "60fc5381fe9f094e56bbb279b857eaec318f5c0f",
            "tree_id": "ff05f721f3f5439824f4d16c074909d63fc34778",
            "distinct": true,
            "message": "Fixed Git SCM book link",
            "timestamp": "2018-11-30T14:54:46-06:00",
            "url": "https://github.com/spring-projects/spring-security/commit/60fc5381fe9f094e56bbb279b857eaec318f5c0f",
            "author": {
              "name": "mibo",
              "email": "mibo@users.noreply.github.com",
              "username": "mibo"
            },
            "committer": {
              "name": "Rob Winch",
              "email": "rwinch@users.noreply.github.com",
              "username": "rwinch"
            },
            "added": [

            ],
            "removed": [

            ],
            "modified": [
              "CONTRIBUTING.md"
            ]
          },
          "repository": {
            "id": 3148979,
            "node_id": "MDEwOlJlcG9zaXRvcnkzMTQ4OTc5",
            "name": "spring-security",
            "full_name": "spring-projects/spring-security",
            "private": false,
            "owner": {
              "name": "spring-projects",
              "email": "",
              "login": "spring-projects",
              "id": 317776,
              "node_id": "MDEyOk9yZ2FuaXphdGlvbjMxNzc3Ng==",
              "avatar_url": "https://avatars0.githubusercontent.com/u/317776?v=4",
              "gravatar_id": "",
              "url": "https://api.github.com/users/spring-projects",
              "html_url": "https://github.com/spring-projects",
              "followers_url": "https://api.github.com/users/spring-projects/followers",
              "following_url": "https://api.github.com/users/spring-projects/following{/other_user}",
              "gists_url": "https://api.github.com/users/spring-projects/gists{/gist_id}",
              "starred_url": "https://api.github.com/users/spring-projects/starred{/owner}{/repo}",
              "subscriptions_url": "https://api.github.com/users/spring-projects/subscriptions",
              "organizations_url": "https://api.github.com/users/spring-projects/orgs",
              "repos_url": "https://api.github.com/users/spring-projects/repos",
              "events_url": "https://api.github.com/users/spring-projects/events{/privacy}",
              "received_events_url": "https://api.github.com/users/spring-projects/received_events",
              "type": "Organization",
              "site_admin": false
            },
            "html_url": "https://github.com/spring-projects/spring-security",
            "description": "Spring Security",
            "fork": false,
            "url": "https://github.com/spring-projects/spring-security",
            "forks_url": "https://api.github.com/repos/spring-projects/spring-security/forks",
            "keys_url": "https://api.github.com/repos/spring-projects/spring-security/keys{/key_id}",
            "collaborators_url": "https://api.github.com/repos/spring-projects/spring-security/collaborators{/collaborator}",
            "teams_url": "https://api.github.com/repos/spring-projects/spring-security/teams",
            "hooks_url": "https://api.github.com/repos/spring-projects/spring-security/hooks",
            "issue_events_url": "https://api.github.com/repos/spring-projects/spring-security/issues/events{/number}",
            "events_url": "https://api.github.com/repos/spring-projects/spring-security/events",
            "assignees_url": "https://api.github.com/repos/spring-projects/spring-security/assignees{/user}",
            "branches_url": "https://api.github.com/repos/spring-projects/spring-security/branches{/branch}",
            "tags_url": "https://api.github.com/repos/spring-projects/spring-security/tags",
            "blobs_url": "https://api.github.com/repos/spring-projects/spring-security/git/blobs{/sha}",
            "git_tags_url": "https://api.github.com/repos/spring-projects/spring-security/git/tags{/sha}",
            "git_refs_url": "https://api.github.com/repos/spring-projects/spring-security/git/refs{/sha}",
            "trees_url": "https://api.github.com/repos/spring-projects/spring-security/git/trees{/sha}",
            "statuses_url": "https://api.github.com/repos/spring-projects/spring-security/statuses/{sha}",
            "languages_url": "https://api.github.com/repos/spring-projects/spring-security/languages",
            "stargazers_url": "https://api.github.com/repos/spring-projects/spring-security/stargazers",
            "contributors_url": "https://api.github.com/repos/spring-projects/spring-security/contributors",
            "subscribers_url": "https://api.github.com/repos/spring-projects/spring-security/subscribers",
            "subscription_url": "https://api.github.com/repos/spring-projects/spring-security/subscription",
            "commits_url": "https://api.github.com/repos/spring-projects/spring-security/commits{/sha}",
            "git_commits_url": "https://api.github.com/repos/spring-projects/spring-security/git/commits{/sha}",
            "comments_url": "https://api.github.com/repos/spring-projects/spring-security/comments{/number}",
            "issue_comment_url": "https://api.github.com/repos/spring-projects/spring-security/issues/comments{/number}",
            "contents_url": "https://api.github.com/repos/spring-projects/spring-security/contents/{+path}",
            "compare_url": "https://api.github.com/repos/spring-projects/spring-security/compare/{base}...{head}",
            "merges_url": "https://api.github.com/repos/spring-projects/spring-security/merges",
            "archive_url": "https://api.github.com/repos/spring-projects/spring-security/{archive_format}{/ref}",
            "downloads_url": "https://api.github.com/repos/spring-projects/spring-security/downloads",
            "issues_url": "https://api.github.com/repos/spring-projects/spring-security/issues{/number}",
            "pulls_url": "https://api.github.com/repos/spring-projects/spring-security/pulls{/number}",
            "milestones_url": "https://api.github.com/repos/spring-projects/spring-security/milestones{/number}",
            "notifications_url": "https://api.github.com/repos/spring-projects/spring-security/notifications{?since,all,participating}",
            "labels_url": "https://api.github.com/repos/spring-projects/spring-security/labels{/name}",
            "releases_url": "https://api.github.com/repos/spring-projects/spring-security/releases{/id}",
            "deployments_url": "https://api.github.com/repos/spring-projects/spring-security/deployments",
            "created_at": 1326232257,
            "updated_at": "2018-11-30T20:25:35Z",
            "pushed_at": 1543611288,
            "git_url": "git://github.com/spring-projects/spring-security.git",
            "ssh_url": "git@github.com:spring-projects/spring-security.git",
            "clone_url": "https://github.com/spring-projects/spring-security.git",
            "svn_url": "https://github.com/spring-projects/spring-security",
            "homepage": "http://spring.io/spring-security",
            "size": 33219,
            "stargazers_count": 2994,
            "watchers_count": 2994,
            "language": "Java",
            "has_issues": true,
            "has_projects": true,
            "has_downloads": true,
            "has_wiki": true,
            "has_pages": true,
            "forks_count": 2779,
            "mirror_url": null,
            "archived": false,
            "open_issues_count": 894,
            "license": {
              "key": "apache-2.0",
              "name": "Apache License 2.0",
              "spdx_id": "Apache-2.0",
              "url": "https://api.github.com/licenses/apache-2.0",
              "node_id": "MDc6TGljZW5zZTI="
            },
            "forks": 2779,
            "open_issues": 894,
            "watchers": 2994,
            "default_branch": "main",
            "stargazers": 2994,
            "main_branch": "main",
            "organization": "spring-projects"
          },
          "pusher": {
            "name": "rwinch",
            "email": "rwinch@users.noreply.github.com"
          },
          "organization": {
            "login": "spring-projects",
            "id": 317776,
            "node_id": "MDEyOk9yZ2FuaXphdGlvbjMxNzc3Ng==",
            "url": "https://api.github.com/orgs/spring-projects",
            "repos_url": "https://api.github.com/orgs/spring-projects/repos",
            "events_url": "https://api.github.com/orgs/spring-projects/events",
            "hooks_url": "https://api.github.com/orgs/spring-projects/hooks",
            "issues_url": "https://api.github.com/orgs/spring-projects/issues",
            "members_url": "https://api.github.com/orgs/spring-projects/members{/member}",
            "public_members_url": "https://api.github.com/orgs/spring-projects/public_members{/member}",
            "avatar_url": "https://avatars0.githubusercontent.com/u/317776?v=4",
            "description": ""
          },
          "sender": {
            "login": "rwinch",
            "id": 362503,
            "node_id": "MDQ6VXNlcjM2MjUwMw==",
            "avatar_url": "https://avatars0.githubusercontent.com/u/362503?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/rwinch",
            "html_url": "https://github.com/rwinch",
            "followers_url": "https://api.github.com/users/rwinch/followers",
            "following_url": "https://api.github.com/users/rwinch/following{/other_user}",
            "gists_url": "https://api.github.com/users/rwinch/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/rwinch/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/rwinch/subscriptions",
            "organizations_url": "https://api.github.com/users/rwinch/orgs",
            "repos_url": "https://api.github.com/users/rwinch/repos",
            "events_url": "https://api.github.com/users/rwinch/events{/privacy}",
            "received_events_url": "https://api.github.com/users/rwinch/received_events",
            "type": "User",
            "site_admin": false
          }
        }
        """.trimIndent()
}