on:
  push:
    branches-ignore:
      - 'gh-pages'
    tags-ignore:
      - '*'
  workflow_dispatch:
env:
  GH_TOKEN_DISPATCH: ${{ secrets.GH_TOKEN_DISPATCH }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          show-progress: false
      - uses: spring-io/spring-gradle-build-action@v2
        with:
          java-version: 17
      - run: ./gradlew check assemble --continue
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          files: |
            build/libs/*.jar